name: build_docs
on:
  push:
    branches:
      - main 

  pull_request:

  schedule:
      - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      configuration: Release
    strategy:
      fail-fast: true
      max-parallel: 4
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          cd ./build/yapre/
          sh ./build_scripts/build_emscripten.sh
          cd ../..
      - name: Copy files to docs
        run: |
          rm -f ./docs/*.*
          cp ./build/yapre/build/emscripten/yapre/* ./docs
      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Github Action Auto Build'
          add: '*.* --force'
          cwd: './docs/'
